In [1]:
import torch

In [2]:
x=torch.empty(5, 3)
print(x)

tensor([[ 1.2549e-37,  0.0000e+00,  1.2432e-37],
        [ 0.0000e+00, -7.6046e-05,  4.5850e-41],
        [-7.0518e-05,  4.5850e-41, -7.0382e-05],
        [ 4.5850e-41, -7.0382e-05,  4.5850e-41],
        [-7.3454e-05,  4.5850e-41, -7.4100e-05]])


## 构建一个未初始化的5x3矩阵

In [3]:
y=torch.rand(5, 3)
print(y)

tensor([[0.9820, 0.0965, 0.2507],
        [0.3553, 0.8512, 0.9202],
        [0.4655, 0.5474, 0.7974],
        [0.9333, 0.5612, 0.5405],
        [0.2055, 0.2009, 0.3155]])


## 构建随即初始化的矩阵

In [3]:
z=torch.zeros(5, 3, dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## 构建一个矩阵填充零

In [4]:
a=torch.tensor([5.5, 3])
print(a)

tensor([5.5000, 3.0000])


## 直接从数据构建张量

In [5]:
a = a.new_ones(5, 3, dtype=torch.double)
print(a)
a = torch.randn_like(a, dtype=torch.float)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8067, -0.3159,  0.2963],
        [ 2.0285,  1.1761, -0.5923],
        [ 1.1680, -0.6273, -1.0236],
        [-0.8552,  1.1433, -0.5143],
        [ 0.9475,  0.1652,  0.5316]])


## 根据现有的张量创建张量。除非用户提供新值

In [6]:
print(a.size())

torch.Size([5, 3])
